### ISSUE TITLE
Need better tutorial example

### ISSUE THREAD

**Issue by michael-prange** [pszufe/OpenStreetMapXPlot.jl#6]
This project seems like it will do what I need, but I need a better tutorial example to learn how to use it. I've downloaded a map of my local area from openstreetmap.org, containing all the roads and trails I'm interested in. Then when I used the tutorial on OpenStreetMapXPlot to plot this data, almost all of the features I see from openstreetmap.org are gone. I've read the code, but I'm not clear on what I need to do to show all the roads, trails and town features.

**Comment by pszufe** [comment]
I am basically using those libraries to plot roads and points of interest (perhaps marked as circles). Plotting "everywhing" to be useful would require some kind of layer management and hence lot's of other API. Moreover, OpenStreetMapX parses only street-related data so it would need to be expended as well. If you are interested in doing that as a PR to the library I can help by explaining how to approach this.
What about the approach presented in this tutorial: https://pszufe.github.io/OpenStreetMapX_Tutorial/
Perhaps would this work for you?

**Comment by michael-prange** [comment]
Thanks. I just peeked inside the map.osm file downloaded from openstreetmap.org <http://openstreetmap.org/> and see that it has everything I need. Then I ran
	m = OpenStreetMapX.get_map_data("/Users/prange/Downloads/Julia Folder/map.osm”);
and peeked inside m. I see that it doesn’t contain the hiking trails I want to plot. When I look at the code for get_map_data() I see
	road_levels::Set{Int} = Set(1:length(OpenStreetMapX.ROAD_CLASSES)),
which means to me that it is grabbing all of the road classes, including unclassified roads and trails, but apparently that isn’t working. I also tried setting only_intersections=false on the methods, but see no difference in results. 

I see in map.osm that the hiking trails are marked as a footway. I suppose I can try to update some OpenStreetMapX methods to include footways in the output from get_map_data(). Then I can see whether plotmap() will plot them.

Michael

**Comment by pszufe** [comment]
this should be fairly easy to do. Please submit the first version of new functionality as a PR and I will review it. I will be also happy to help if you get stuck at any point.

**Comment by michael-prange** [comment]
Thanks.

**Comment by michael-prange** [comment]
All I needed to do was to set
	OpenStreetMapX.ROAD_CLASSES["footway"]=8
before calling get_map_data() and the trails were plotted. I’m not sure if 8 is appropriate for a footway, but it is also used for pedestrian, so it seemed right.

Thanks for your help.

Michael

**Comment by michael-prange** [comment]
I seem to have uncovered an issue with plotting my hiking track on a map. As the attached PDF notebook of my Julia session shows, the issue seems to be in the conversion of the track LLA coordinates into ENU coordinates. Perhaps I’m just using the package incorrectly. Perhaps you can take a peek and advise.

Michael

**Comment by pszufe** [comment]
`ENU` coordinates are local (attached to some starting point) while `LLA` coordinates are global. Hence converting between the two you need to provide that point. This is achieved by passing to constructors the `bounds` field present in the `MapData` object. If you still have problem copy paste the code here.

**Comment by michael-prange** [comment]
I applied the map bounds to do the conversion. See In[12] in the attached pdf.

**Comment by pszufe** [comment]
There is no attachment. Probably you should answer via GitHub website.

**Comment by michael-prange** [comment]
[OpenStreetMapX Notes.pdf](https://github.com/pszufe/OpenStreetMapXPlot.jl/files/4264754/OpenStreetMapX.Notes.pdf)

**Comment by pszufe** [comment]
`addroute!` is plotting a list of nodes rather than a list of coordinates. You actually normally use `addroute!(p, m::OpenStreetMapX.MapData, route::Vector{Int})` so the first parameter is your parsed map and the second is the list of OSM nodes. 
As far as I understand you have some data from GPS devices I would recommend implementing another `addroute!`  that takes actual coordinates to plot. 
Another option is to map the series your GPS coordinates to OSM nodes and than use the current implementation but that would be definitely more complex and less useful.

**Comment by michael-prange** [comment]
I've followed your advise and created a new addroute!() that takes an array of LLA coordinates and plots it on the map. I'm not sure how to submit my new function, so here it is. I've added my notes as a PDF:
[OpenStreetMapX Notes.pdf](https://github.com/pszufe/OpenStreetMapXPlot.jl/files/4268097/OpenStreetMapX.Notes.pdf)


```
"""
    addroute!(p, m::OpenStreetMapX.MapData,
                   route::Vector{OpenStreetMapX.LLA}; 
                   route_color::String ="0x000053",
                   km::Bool=false, 
                   start_name="A", end_name="B", 
                   fontsize=15
                   ) where T<:Union{OpenStreetMapX.LLA,OpenStreetMapX.ENU}
                   
Adds a `route` in LLA coordinates to the plot `p`.

The first element from the list of route coordinates `route` will be annoted by `start_name` 
while the last will be annotated by `end_name`.
    
Returns an object that can be used for further plot updates.
                   
"""
function OpenStreetMapXPlot.addroute!(p, m::OpenStreetMapX.MapData,
                   route::Vector{OpenStreetMapX.LLA}; route_color::String ="0x000053",
                   km::Bool=false, start_name="A", end_name="B", fontsize=15)
    osm_use_pyplot = (p == :osm_use_pyplot)
    route_style = OpenStreetMapXPlot.Style(route_color, 3, "--")
    routeENU = [ENU(lla, m.bounds) for lla in route]
    X = map(enu->enu.east, routeENU)
    Y = map(enu->enu.north, routeENU)

    if km
        X /= 1000
        Y /= 1000
    end
    if length(X) > 1
        if !osm_use_pyplot
            Plots.plot!(p, X, Y, color=route_style.color,width=route_style.width,linestyle=gr_linestyles[route_style.spec])
            Plots.annotate!(p,X[1],Y[1],Plots.text(start_name,fontsize))
            Plots.annotate!(p,X[end],Y[end],Plots.text(end_name,fontsize))
        else
            PyPlot.plot(X, Y, color=route_style.colorPyPlot,linewidth=route_style.width,linestyle=route_style.spec)
            PyPlot.text(X[1],Y[1],start_name,fontsize=fontsize)
            PyPlot.text(X[end],Y[end],end_name,fontsize=fontsize)
        end
    end
    p
end
```

**Comment by pszufe** [comment]
Thank you for the PR.
Since someone is actually using that package I will do a clean-up and a proper registration in the Julia package repository so you will not need a full GitHub path when installing it.

**Comment by pszufe** [comment]
Last but not least - if you decide that you want to add something else and need another PR, the easiest way is to delete your fork and make a fork again and again clone it to your machine etc. Otherwise, the synchronization of all versions is requires crazy amount of steps (not good for your first PRs)

**Comment by michael-prange** [comment]
Should I delete the fork now?

**Comment by pszufe** [comment]
1. The fork is not needed anymore since I merged your changes so you can safely delete it
2. If you ever want to make another PR you will need either delete the fork and create it again OR follow these instructions https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by michael-prange** [comment]
Thanks again. I've deleted the repository.
